### ISSUE TITLE
checkbox not appears

### ISSUE THREAD

**Issue by joiel** [tonystar/float-label-css#22]
```
<div class="form-group">
                                        <label class="custom-control custom-checkbox">
                                            <input class="custom-control-input" type="checkbox"/>
                                            <span class="custom-control-indicator"></span>
                                            <span class="custom-control-description">Subscribe to newsletter</span>
                                        </label>
                                    </div>
```
![image](https://user-images.githubusercontent.com/12823424/34940761-6903aaaa-fa23-11e7-86cb-ae9dd906a91d.png)

**Comment by tonystar** [comment]
@joiel any difference between subscribe checkbox and remember? can you probably attach html/zip?

**Comment by joiel** [comment]
yeah.

subscribe im using yours. and remember im using plain.

`<div class="form-group">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> Remember Me
                                            </label>
                                        </div>
                                    </div>`

**Comment by tonystar** [comment]
Checkboxes do not use float labels, simply use plain ones!

If you want, say, custom Bootstrap checkboxes - refer here http://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios-1.

**Comment by joiel** [comment]
hm but im using bs 3 css

**Comment by joiel** [comment]
ill close this thread since im prefer using plain one. thank you for your support really appreciate!
