### ISSUE TITLE
Float label select

### ISSUE THREAD

**Issue by dobromir-bogatev** [tonystar/float-label-css#23]
I can see that you have CSS for select tag, but I cant see a demo and I cant seem to figure out how exactly it is supposed to work.
Kudos for this. I searched a lot for no JS floating label input.

**Comment by dobromir-bogatev** [comment]
Turns out I havent noticed that this question was already asked. Im sorry. Im closing the issue.

**Comment by tonystar** [comment]
@dobromir-bogatev no worries!

Ref: https://github.com/tonystar/float-label-css/issues/18
